### ISSUE TITLE
ts__default$1.default.isTypeAssertionExpression is not a function (ts)

### ISSUE THREAD

**Issue by mejgun** [sveltejs/language-tools#685]
**Describe the bug**
after update to 1.1.15 svelte-check returns error on each svelte component
```
<component>.svelte:NaN:1
Error: ts__default$1.default.isTypeAssertionExpression is not a function (ts)
```

project builds and works ok, vscode shows no error

**To Reproduce**
`npm upgrade && npx svelte-check`

**System (please complete the following information):**
 - OS: Linux
 - IDE: VSCode
 - Plugin/Package: svelte+TS

**Additional context**
```
  "devDependencies": {
    "@rollup/plugin-commonjs": "^14.0.0",
    "@rollup/plugin-node-resolve": "^8.0.0",
    "@rollup/plugin-typescript": "^6.1.0",
    "@tsconfig/svelte": "^1.0.0",
    "rollup": "^2.33.3",
    "rollup-plugin-livereload": "^2.0.0",
    "rollup-plugin-svelte": "^6.1.1",
    "rollup-plugin-terser": "^7.0.0",
    "svelte": "^3.29.7",
    "svelte-check": "^1.1.15",
    "svelte-preprocess": "^4.6.1",
    "tslib": "^2.0.3",
    "typescript": "^3.9.7"
  }

```

**Comment by dummdidumm** [comment]
Try upgrading TypeScript to the latest version. It seems like the `isTypeAssertionExpression` function got added only recently to TypeScript, which we are using inside `svelte-check`. @jasonlyu123 should we maybe fall back to using a "handcrafted" version of that function?

**Comment by mejgun** [comment]
> Try upgrading TypeScript to the latest version. It seems like the `isTypeAssertionExpression` function got added only recently to TypeScript, which we are using inside `svelte2tsx`.

Thanks. Problem solved :-)
