### ISSUE TITLE
"Cannot find module" error from language server when importing `.svelte` file from `.ts` file

### ISSUE THREAD

**Issue by DetachHead** [sveltejs/language-tools#1457]
### Describe the bug

seems to have been caused by #1448

now when importing a `.svelte` file from within a `.ts` file, the language server thinks the `.svelte` file doesn't exist

### Reproduction

```ts
import App from './App.svelte' //error: Cannot find module './App.svelte' or its corresponding type declarations.

const app = new App({
    target: document.getElementById('app'),
})
export default app
```

### Expected behaviour

- no error when the `.svelte` file exists
- error when the `.svelte` file doesn't exist

### System Info

- OS: windows 10
- IDE: vscode

### Which package is the issue about?

language-server

### Additional Information, eg. Screenshots

![image](https://user-images.githubusercontent.com/57028336/164618225-b09430be-b0bf-4a5d-a831-036ce578efaa.png)
![image](https://user-images.githubusercontent.com/57028336/164618362-1085fef3-f67c-4f17-972f-f6cbda63f60a.png)

**Comment by jasonlyu123** [comment]
Does it always happen on your machine? I can't reproduce this. Can you provide a reproducible repository?

**Comment by DetachHead** [comment]
that's strange, i re-`npm install`'d and restarted the language server and the error went away. will reopen and try to provide more info if it happens again, sorry
